piceaTech/node-gitlab-2-github

index.js
To fix issue #3 (see more details in the issue description)
Please let me know if you have any comment.
=> fix import if github already have milestones

index.js
Hi @spruce,
I implemented support for labels similar to support for milestones - works great for me!
Issue needed? Just let me know.
=> Support for labels

index.js
- Add placeholder issues if issues are missing in github to ensure issue id remains the same
- Added a few semi-colons
Thanks for merging.
Andres
=> Add placeholder issues if issues are missing in github to ensure issue id remains the same

index.js, sample_settings.json
Moving issues from an organisation repository is only possible if
the username is different from the owner name.
=> Add different repo owner support

index.js, package.json
Update node-github and use newer API version.
=> Update GitHub API

README.md
@spruce 
> io.js has merged with the Node.js project again.
Plus adding empty lines for titles
=> No more io.js

README.md, index.js, package-lock.json, package.json, sample_settings.js
This PR is essentially a complete overhaul of the code, but it contains the same behavior and functionality. I replaced the deep nested promises with `async` and `await` to enhance readability. Additionally, I made functions smaller and eliminated some global variables.
=> Restructure of code to use modern syntax such as async/await

.gitignore, README.md, index.js, package-lock.json, package.json, sample_settings.js
I added some docs and set debugging default to false.
Closes #35
=> Beamer15 update apis

index.js
Fixed only the first gap being filled. Now each placeholder has a different identifier.
=> placeholder fix

index.js
=> fixed merge request undefined number (again)

.gitignore, .prettierrc, README.md, index.js, package-lock.json, package.json, sample_settings.js
I added prettier + a config file for prettier to the repo. There will be more pull requests coming from my side in the upcoming days, and i think it makes sense that every contributor of this project uses the same formatting settings.
This commit also adds a few entries to the .gitignore file.
=> Basic setup changes

index.js
=> Fix bug that occurs for successive missing gitlab issues

index.js
=> Avoid creating dup github issue from gitlab merge request (fixes #65)

githubHelper.js
If not pushing to GitHub then this does nothing.
=> Include link to diff in GitHub from in-line MR comments.

README.md, sample_settings.ts, src/index.ts, src/settings.ts
This will allow the specification of which content to transfer via the settings file.
=> Adding Ability to specify which content to transfer.

src/githubHelper.ts
If we try and transer a new PR which has been merged but the
source branch was not deleted, we previously got a 422 status and
the transfer failed. Modify the logic to pick up the 422 status
and, if seen, fall back to creating an issue.
Fixes #91
=> Handle scenario where new PR branch has been merged

package.json, src/index.ts
=> Pause for an extra 60 secs after abuse limit errors before retrying

sample_settings.ts
* Fixed a typo in `sample_setting.ts`
=> Fixed typo

src/githubHelper.ts, src/index.ts
This fixes some (but not all) issues mentioned in https://github.com/piceaTech/node-gitlab-2-github/issues/167
=> Use more precise match when searching for duplicate issues

src/githubHelper.ts
=> Only set gitlab merge request label if the item is an MR

src/githubHelper.ts
=> Ensure assignees are members of the organization
