piceaTech/node-gitlab-2-github

index.js

- d13eebcb broke the milestone creation for me because `data.title` does not contain the array of milestone titles
- var `err` is in fact undefined in index.js#L70, therefore passing `null`. I believe this is the actual issue

fixes #3 in a different way

---

index.js
sample_settings.json

Hi @spruce,
I made github url and pathPrefix configurable to support GitHub enterprise - works great for me!
Thanks for merging.
Andres

Made github url and pathPrefix configurable to support GitHub enterprise

---

index.js
sample_settings.json

Hi @spruce,
I added support for username mapping:
- Allow to define username mapping in settings
- Assign issues to github username
- Replace mentions (@username) with guthub username
- Add line at the beginning of issues and comments indicating
author and timestamp because this gets lost during the migration
Thanks for merging.
Andres

Support for username mapping

---

index.js
sample_settings.json

Hi @spruce,
I added a number of things, I hops it's not too much
- Refactored regular expression which is used to replace usernames and cross-project issue references to be created exactly once
- Label issues which have an attachment with a label 'hasAttachment' for manual migration
- Skipping 'Added label' issue comments
- Support for cross-reference issue mapping (similar to username mapping) for cases where a project is moved or renamed during migration
- Formatting dates in the migration comment line to e.g. "Apr 12, 2016, 10:30"
Thanks for merging.
Andres

Label issues with attachments, skip 'Added label' issue comments, support for cross-reference issue mapping

---

README.md
index.js
package.json

the previous version of the github bindings did not play nicely when using a
proxy (I can illustrate details if desired). the newer version of the bindings
seems to work, with some tweaks to the function names in the bindings.
thanks so much, this lib was super useful!
fwiw, the milestone refs and issue refs do not seem to be rewritten properly,
I am not sure if this could somehow be related to updating these bindings (it
seems not, but idk). specifically, milestones show up like `%4` in comments
and issue refs like `#42` do not remap to the `#42` from gitlab under the new
issue number in github. @ references are remapped properly (yay). I'm sorry
that I did not take the time to fix these, but highlighting for future users
who may be interested in doing so!

update to latest github bindings

---

index.js

Add a `null` value to the `iid` field of the placeholder item for (likely) deleted GitLab issues, and a check in the `createIssueComments` comments function for the null iid value. A message is added to the log indicating that no comments are retrieved for the placeholder issue.

elegant failure when retrieving notes for placeholder issue

---

README.md
index.js
package-lock.json

Ok, so I've spent some time implementing code that migrates merge requests from GitLab to GitHub. Such migrations are not always possible; for example, if a merge request on GitLab deletes the source branch after the merge is made, an identical pull request cannot be created on GitHub because the source branch no longer exists. To work around this, I create an issue with a special "gitlab merge request" label that contains the full comment history of the merge request.
Another change I made while implementing this code is to change the order that content is migrated. The order is now Milestones, Labels, Issues, and Merge Requests. This guarantees that the Issues have the same issue numbers in both platforms. GitHub pull requests are just a special type of issue, so they are assigned issue …

Migrate merge requests

---

README.md
index.js
package-lock.json
package.json
sample_settings.js

Hey
In order to fix https://github.com/piceaTech/node-gitlab-2-github/issues/49#issuecomment-554681996 I updated the `gitlab` package to its most recent version.
Made some other small improvements:
- added required scopes to the readme (https://github.com/piceaTech/node-gitlab-2-github/issues/61)
- added further suggestion for skipping comments based on content
- added the default GL url as default, so it's consistent with the GH options
- added a generic error logging to the transfer process - http error details are visible this way
- removed redundant param from `transferMilestones`, this also makes it consistent with other similar functions
If you don't like something though, feel free not to merge it.
Tested the basic process except for milestones (wasn't included in my use case). But …

Update `gitlab` package and minor improvements

---

README.md
sample_settings.ts
src/githubHelper.ts
src/index.ts

This is a simple way to create all the merge requests in the same place, particularly as GitHub throws
an error when pull requests have invalid branches, and this results in nothing being created.
Leave this turned off by default for consistency.

Add option to always migrate merge requests as issues.

---

src/settings.ts

Hello.
I was using this script to migrate my blog's code from GitLab to GitHub.
I found a problem with it and will fix it.
It seems that a setting for useIssuesForAllMergeRequests was added the other day, but the interface, src/settings.ts, didn't have a type definition in it, so it was causing an error at runtime.
```
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:72:48 - error TS2339: Property 'useIssuesForAllMergeRequests' does not exist on type 'Settings'.
72                                       settings.useIssuesForAllMergeRequests);
```
So I've added the setting.

add useIssuesForAllMergeRequests to interface

---

src/index.ts

This PR only moves the computation to the beginning of the transfer, irrespective of what is transferred. Closes #114

Closes #114: always compute gitlab project path

---

README.md
sample_settings.ts
src/githubHelper.ts
src/gitlabHelper.ts
src/settings.ts
src/utils.ts

This PR:
* Closes #107: uses a hash of the attachment's URL to avoid duplicates upon failure
* Closes #103: Doesn't fail if there was an error downloading an attachment
* Closes #106: migrates arbitrary attachment types using a browser cookie (workaround for [GitLab's missing API endpoint](https://gitlab.com/gitlab-org/gitlab/-/issues/24155))
* Uses previous attachment URL if S3 is not configured

Fixes for S3 attachments

---

.gitignore
.prettierrc
package-lock.json
package.json
src/githubHelper.ts
src/index.ts

This PR:
* Updates octokit and gitbeaker to their latest versions
* Updates used types in the code to conform to the new library versions. In particular, it fixes #89
* Updates husky, prettier, and several other libraries
* Updates setting of AWS to avoid using deprecated properties, using instead [AWS.Credentials()](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#constructor-property)
Additionally (sorry for mixing this in)
* It installs husky upon `npm i` to ensure git hooks are always installed
* Removes `package-lock.json` from `.gitignore` since it should be committed to pin the right versions.
Many changes in the commits are just formatting issues fixed by prettier

Update octokit, gitbeaker and others

---

README.md
sample_settings.ts
src/githubHelper.ts
src/gitlabHelper.ts
src/index.ts
src/settings.ts

This PR:
* adds an option to use the preview API for issue imports. This enables setting the creation and modification date of issues and comments.
* documents it
* adds `settings.github.token_owner`. Required to check ownership of comments against the user creating the new content on GH.
Additionally, it:
* caches a call to getAllBranches()
* Fixes a typing problem in https://github.com/piceaTech/node-gitlab-2-github/blob/7572017dfbcb0a7a2a8917ab6cb99ebe2c173877/src/githubHelper.ts#L858
* Fixes a problem whereby labels are not converted to lowercase before using them in `createIssue()`: https://github.com/piceaTech/node-gitlab-2-github/blob/7572017dfbcb0a7a2a8917ab6cb99ebe2c173877/src/githubHelper.ts#L258

New feature: Option to use issue import preview API

---

README.md
sample_settings.ts
src/index.ts
src/settings.ts

This PR adds a new config variable `skipMergeRequestStates` which is an array of strings. Merge requests with a state listed in this array will not be migrated. Closes #105

Skip merge requests in given states

---

src/githubHelper.ts

This PR skips more notes from the history of changes to issues, including assignment, title changes, label changes, and others.

Added some regexes to skip issue notes

---

README.md
sample_settings.ts
src/githubHelper.ts
src/index.ts
src/settings.ts

Added code to transfer releases from gitlab to github with limited functionality (due to github api limitations).

feat(releases): migrate releases from gitlab to github

---

sample_settings.ts
src/githubHelper.ts
src/index.ts
src/settings.ts

This patch enables copying the project description from GitLab as the repository description on GitHub. Control characters disallowed by GitHub (like newlines) are turned into whitespace. No attempt is made to translate anything else like Markdown links or other formatting.

Transfer repository description by default

---

.vscode/launch.json
README.md
package-lock.json
package.json
sample_settings.ts
src/githubHelper.ts
src/index.ts
src/settings.ts

This is useful when debugging: set `settings.github.recreateRepo: true` and given the access token `delete_repo` rights to always delete and recreate the destination repository before migrating.

Option to recreate GitHub repository

---

README.md

Update gitlab personnal access token link

---

src/index.ts

Alternate approach to #109, using `plugin-throttling` `minimumAbuseRetryAfter` instead of `sleep`.
I used [this discussion](https://github.community/t/what-are-the-rules-behind-you-have-triggered-an-abuse-detection-mechanism/164457/4) to guide this solution.
Fixes #28

Throttling mechanism to manage content creation abuse rate limit

---

src/gitlabHelper.ts

Use HTTPS instead of HTTP as the default GitLab value.
The problem was that atachment downloading didn't work with the default `http` value after switching to `https` the attachment downloading started working.

Use https instead of http as default gitlab value

---

README.md
sample_settings.ts
src/gitlabHelper.ts
src/settings.ts

This adds support to filter out archived GitLab projects on the first run, when listing projects.
For compatibility reasons I have kept this option true by default, i.e. archived projects will be included in the list.

Add support to filter out archived GitLab projects

---

.dockerignore
Dockerfile
Makefile
README.md
src/gitlabHelper.ts

With this PR:
* Add `Dockerfile`, so people with no Node.js installed in their local environments can simply create a Docker container to run the migration process;
* Update the README with usage instructions for the Dockerfile;
* Add `.dockerignore` to avoid copying some files to the container;
* Add `Makefile` to make it easier to run the Docker commands.
Let me know if there is anything you guys would like to change. I have tested this locally and it worked fine.

Dockerize this application

---

src/githubHelper.ts

Prior to this change, we would ignore the
```
await this.githubApi.pulls.create(props);
```
return value, which is the actual Pull Request data. As a result, none of the logic beyond creating the Pull Request could run: https://github.com/piceaTech/node-gitlab-2-github/blob/master/src/githubHelper.ts#L792
It looks like https://github.com/piceaTech/node-gitlab-2-github/commit/d65ac3f72f02ed5b670e847e278d4c736a7f5f1a caused this issue, but I'm not sure if my solution causes a regression.

Enable note migration by resolving correct response

---

src/index.ts

This fixes JavaScript errors with newer GitLab repositories where description is null.

Transfer description only when it exist

---

sample_settings.ts
src/githubHelper.ts
src/index.ts
src/settings.ts

- Now when labels are transferred, their descriptions are as well!  
- Added some color options for your console output, feel free to use elsewhere :)
- `trimOversizedLabelDescriptions` boolean option to trim them to the maximum allowable length instead of leaving blank, maybe a bit excessive feel free to remove this logic.

Feature: transfer label descriptions

---

README.md
sample_settings.ts
src/githubHelper.ts
src/index.ts
src/settings.ts

Hi, I think the project is not being actively maintained, but leaving this PR here in case someone else needs a list of the users from the comments/notes/labels/etc. in order to create the user map.
I didn't worry about adding a test, or verifying if I were adding users in an optimal way due to time. It simply uses a `Set` and adds everything it finds when the code touches `usermap`, and later dumps this list in a `users.txt` file. You can then use this list from GitLab users to locate their GitHub user Ids, and create a usermap (i.e. first use `dryRun`).
cc @LuiggiTenorioK

Add option to save a list of users

---

src/githubHelper.ts

Hi! I saw that there was an error on the last PR https://github.com/piceaTech/node-gitlab-2-github/pull/205 we submitted with @kinow about the list of users.
The problem is that in the final GitLab user list, the already converted usernames from GitHub were added to the list instead of the GitLab ones when converting the issues/comments.
This quick fix only moves that code snippet to the right place (before converting the username).

Fix GitLab username saved after conversion

---

src/githubHelper.ts

Datetimes on GitLab and GitHub generally include the timezone when hovering over the datetime.
Include the timezone in the migration line so that it is clear what timezone the mentioned datetime corresponds to since the shown datetime depends on the timezone the tool is executed in.

Include timezone in date format of migration line

---

src/gitlabHelper.ts

GitLab seems to have changed the URL for attachments.
Previously, it was `gitlab.com/<group>/<project>/uploads/<file>`, whereas now it is `gitlab.com/-/project/<projectId>/uploads/<file>`.
While old attachment URLs still work, it seems that new attachments can only be retrieved under the new URL.
In the UI, the link also goes to the new URL (for all of them).

Change GitLab attachment URL to current one

---

src/githubHelper.ts

The anchor in diff links is currently broken.
It looks like GitHub changed the hash function to `sha256` from `md5`.

Change hash function for diff anchor to sha256

---

src/githubHelper.ts

Add the label `merged` to the PR if merge request was merged on GitLab.
Also added the `gitlab merge request` label to be consistent with what is done with issues.
This helps to know that this was previously a merge request on GitLab.
Fixes #209

Add merged label to PR if the MR was merged

---

src/githubHelper.ts
src/index.ts

Throw an error when the max length of the body is exceeded.
In order for the execution to stop and not continue with the remaining merge requests it is necessary to `break` here: https://github.com/piceaTech/node-gitlab-2-github/blob/6b1d903b728399f857d7f536c78ee6e32d858215/src/index.ts#L587-L592
If this is desired, I can add it.
Fixes #208

Detect when MR has a description that is too long

---

src/githubHelper.ts

Replaces `github.com` in URLs with `redirect.github.com` to avoid backlink spam.
This is only done when the URL points to outside of the owner of the GitHub namespace, e.g., the organization, to keep internal backlinks.
Fixes #211

Replace GitHub URLs outside of the owner namespace to avoid backlink spam

---

src/githubHelper.ts

Follow-up from https://github.com/piceaTech/node-gitlab-2-github/pull/213#issuecomment-2616650451 where I suggested to add the `web_url` link to GitLab for future reference.

Add link to original item on GitLab

---

src/index.ts

Merge requests with a "duplicate title" were not migrated.
With the addition of the GitLab URL of the migrated item in #219 it is now possible to use that to detect if an item was already migrated.

Detect existing issues by title and GitLab URL to avoid skipping an item

---

src/githubHelper.ts
src/gitlabHelper.ts

Use discussions instead of notes when migrating merge requests.
Discussions provide the threads and individual comments on MRs.
Each discussion is converted into one comment on GitHub.
This also has the benefit of being able to link to the line that a comment was made one during code review.
Fixes #210

Use discussions instad of notes

---

src/gitlabHelper.ts

It happened to me a few times and I found it helpful to hint at it.

Add hint about expired session cookie if attachment retrieval fails

---

README.md
sample_settings.ts
src/githubHelper.ts
src/gitlabHelper.ts
src/settings.ts
src/utils.ts

Information about assignees and reviewers (and whether they approved) can get lost when migrating, especially if the users don't exist on GitHub, or are not part of the same organization (anymore).
This PR adds assignees (issue and MR), reviewers (MR only), and approvals (MR only) to the end of the body of a migrated merge request (just above the "Migrated from ..." line).

Add information about assignees, reviewers, and approvers to body

---

Dockerfile
package-lock.json
package.json
src/index.ts

Upgrade octokit packages. In particular, `plugin-throttling` which handles the current best practices in avoiding being rate limited.
Fixes #189 
Fixes #90 
Should also fix #222

Improve rate limit handling

---

src/gitlabHelper.ts

The previous change in #232 used the wrong endpoint to determine MR approvals.

Use correct endpoint for determining MR approvals
